#!/bin/bash

# AccounTech AI Deployment Script
# Domain: etherium.group

set -e

echo "🚀 Starting AccounTech AI Deployment..."

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed. Please install Docker first.${NC}"
    exit 1
fi

# Check if Docker Compose is installed
if ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}❌ Docker Compose is not installed. Please install Docker Compose first.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Docker and Docker Compose are installed${NC}"

# Create necessary directories
echo "📁 Creating directories..."
mkdir -p nginx/certs nginx/vhost.d nginx/html nginx/acme
mkdir -p backend/data

# Check if app_password.txt exists
if [ ! -f "backend/app_password.txt" ]; then
    echo -e "${YELLOW}⚠️  Creating default password file...${NC}"
    echo "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918" > backend/app_password.txt
    echo -e "${GREEN}✅ Default password: admin${NC}"
fi

# Stop existing containers
echo "🛑 Stopping existing containers..."
docker-compose -f docker-compose.prod.yml down 2>/dev/null || true

# Build images
echo "🔨 Building Docker images..."
docker-compose -f docker-compose.prod.yml build --no-cache

# Start services
echo "🚀 Starting services..."
docker-compose -f docker-compose.prod.yml up -d

# Wait for services to be healthy
echo "⏳ Waiting for services to start..."
sleep 10

# Check service status
echo "📊 Checking service status..."
docker-compose -f docker-compose.prod.yml ps

# Initialize database
echo "🗄️  Initializing database..."
docker exec accountech-backend python init_db.py || echo -e "${YELLOW}⚠️  Database already initialized${NC}"

echo ""
echo -e "${GREEN}✅ Deployment completed successfully!${NC}"
echo ""
echo "🌐 Your application is now available at:"
echo -e "   ${GREEN}https://etherium.group${NC} (Frontend)"
echo -e "   ${GREEN}https://api.etherium.group${NC} (Backend API)"
echo ""
echo "🔐 Default credentials:"
echo -e "   Username: ${YELLOW}admin${NC}"
echo -e "   Password: ${YELLOW}admin${NC}"
echo ""
echo "📝 SSL certificates will be automatically generated by Let's Encrypt"
echo "   This may take a few minutes..."
echo ""
echo "📊 To view logs:"
echo "   docker-compose -f docker-compose.prod.yml logs -f"
echo ""
echo "🛑 To stop services:"
echo "   docker-compose -f docker-compose.prod.yml down"
echo ""
